name: TeleportWay
version: '0.1.0'
main: com.umnirium.mc.teleportway.TeleportWay
description: TeleportWay is the ultimate teleportation and spawn management solution for Minecraft servers.
author: ixcharles
website: https://github.com/ixcharles
api-version: '1.21.5'