name: TeleportWay
version: '0.2.0'
main: com.umnirium.mc.teleportway.TeleportWay
description: TeleportWay is the ultimate teleportation and spawn management solution for Minecraft servers.
author: ixcharles
website: https://github.com/ixcharles
api-version: '1.21.5'
permissions:
  teleportway.command.*:
    description: Gives access to all TeleportWay commands
    children:
      teleportway.command.setspawn: true
      teleportway.command.spawn: true
      teleportway.command.delspawn: true
  teleportway.command.setspawn:
    description: Set custom spawn
    default: op
  teleportway.command.spawn:
    description: Teleport to spawn
    default: op
  teleportway.command.delspawn:
    description: Delete spawn
    default: op